### ISSUE TITLE
TBPROTO: EKM language is flawed (was: Clarifying Token Binding behavior with renegotiation)

### ISSUE THREAD

**Issue by equalsJeffH** [TokenBinding/Internet-Drafts#75] opened 2016-11-13 05:33 UTC
See: https://www.ietf.org/mail-archive/web/unbearable/current/msg00908.html
@Andrei-Popov : "It is true that in TLS, a session can outlast a connection, and also a connection can outlast a session. The intent in the TBPROTO I-D is that the current EKM be used, that is, the one from the latest TLS session or connection. I agree that the existing language in the I-D is over-simplified and does not fully convey this; will clarify in the next revision."

see also: https://www.ietf.org/mail-archive/web/unbearable/current/msg00913.html
issue: ekm language flawed
"If the latest EKM is required after renegotiation (as it currently is, albeit admittedly the language is flawed)"

**Comment by Andrei-Popov** [comment] 2016-11-17 06:05
Closing as a dupe of #73.

**Closed as completed by Andrei-Popov** 2016-11-17 06:05 UTC
