### ISSUE TITLE
TBPROTO: Clarify hazards of renegotiation wrt Token Binding

### ISSUE THREAD

**Issue by equalsJeffH** [TokenBinding/Internet-Drafts#76] opened 2016-11-13 09:00 UTC
see: https://www.ietf.org/mail-archive/web/unbearable/current/msg00929.html

@martin-thomson : "I am very happy to see text that explains the hazards of renegotiation in this context and that initiators of renegotiation should ensure that they line their ducks up correctly (with all the ins-and-outs, etc...)."

@Andrei-Popov : "I'll add some text to this effect in the next revision."

**Comment by Andrei-Popov** [comment] 2016-11-17 04:44
Closing as a dupe of issue #75.

**Closed as completed by Andrei-Popov** 2016-11-17 04:44 UTC
